### ISSUE TITLE
selecting "Open Aerial Settings" crashes app

### ISSUE THREAD

**Issue by ckuhtz** [AerialScreensaver/Aerial#61] opened 2023-06-21 18:56 UTC
Aerial Companion 1.5.0beta5
13.4 Ventura

When I launch Aerial Companion, it fires up, I can select it from menu bar, but if I click on the gear for "Open Aerial Settings", the app crashes instantly.

When I run the app from CLI, I get this:

```
~ % /Applications/Aerial\ Companion.app/Contents/MacOS/Aerial\ Companion
update
setIcon normal
update
setIcon normal
update
update
2023-06-21 11:51:41.707 Aerial Companion[1789:18166] WOOO /Users/christian/Library/Screen Savers/Aerial.saver/Contents/MacOS/Aerial
2023-06-21 11:51:41.717 Aerial Companion[1789:18166] Bundle loaded
2023-06-21 11:51:41.717 Aerial Companion[1789:18166] av : AerialView
2023-06-21 11:51:42.005 Aerial Companion[1789:18166] Warning: Column selection is not supported in view-based table and outline views (<NSTableView: 0x128091e00>).
update
zsh: trace trap  /Applications/Aerial\ Companion.app/Contents/MacOS/Aerial\ Companion
```

Any ideas on what to try here?

**Comment by glouel** [comment] 2023-06-21 18:58
Hey @ckuhtz 

Bit of context, did you use the previous betas or not ? 

Also can you go into System Settings, see if you don't have 2 versions of Aerial installed by any chance, and check which version the one you see reports ?

**Comment by glouel** [comment] 2023-06-21 19:15
Just come to mind, in companion settings, make sure you have yes to betas of Aerial too, I can see it crashing with 3.2.6 if that's what you have for the screensaver. I should have mentionned that in the release notes.

![Capture d’écran 2023-06-21 à 21 14 41](https://github.com/AerialScreensaver/AerialCompanion/assets/37544189/8c867ccf-320d-4236-af29-1a6047224ef1)

**Comment by ckuhtz** [comment] 2023-06-22 02:31
> Bit of context, did you use the previous betas or not ?

I tried the 1.4something version and saw the same thing.  And I got the same thing initially with the original 3.2.6 and the beta.

That said, I had one successful attempt the first time I tried 3.2.6 on this machine to try to open the options.  After that, no go. Not with several of the betas.

I've tried removing the plist, Caches etc manually in an attempt to troubleshoot after uninstalling, and no change.

> Also can you go into System Settings, see if you don't have 2 versions of Aerial installed by any chance, and check which version the one you see reports ?

There's only one.

Is there any way to determine what causes the crash?  A log somewhere?

**Comment by ckuhtz** [comment] 2023-06-22 02:32
> Just come to mind, in companion settings, make sure you have yes to betas of Aerial too, I can see it crashing with 3.2.6 if that's what you have for the screensaver. I should have mentionned that in the release notes.

Yes, betas are turned on. And I clicked on check as well.  In the original and several of the betas for the companion i tried.

**Comment by glouel** [comment] 2023-06-22 13:09
Ok first thanks a lot for reporting this, and let's me try and rewind a bit, because I think I went the wrong direction with my suggestions.

Because there are multiple moving parts, I thought initially maybe it was Companion that was the issue, but it may be the screen saver settings themselves that are crashing. 

Question : 
- I assume that the screensaver itself runs when you start it manually or it launches itself ? We're talking specifically about settings not opening ? 
 
Here's a few things to try : 
- First, go into System Settings (if it was opened, close it first, then reopen it just in case), Screen Savers, Aerial should be picked. What happens if you press the options button ? This only works once usually on Ventura because of some bugs with System Settings which doesn't help. So if you want to try again, close System Settings and reopen it.  I'd like to see if it's just the panel opening that crashes for you and not Companion doing it, if that makes sense. 

- Second, regarding crash logs, open `console.app` on your mac, in the left column there's a section for crashes, you should see crash reports for either : `legacyScreenSaver`, `ScreenSaverEngine`, `Aerial Companion`, `System Settings` or something Aerial-y (Aerial Updater maybe). If you have any, please attach them.

- Third, Aerial does have logs but I disabled them by default recently (...), but you can likely enable them easily if you are familiar with terminal. I would suggest first in a terminal try : 

```
defaults read ~/Library/Containers/com.apple.ScreenSaver.Engine.legacyScreenSaver/Data/Library/Preferences/com.glouel.Aerial.plist
```

This should output a bunch of configuration. If it doesn't let me know. If it does, please paste it. 

Then to enable logs : 

```
defaults write ~/Library/Containers/com.apple.ScreenSaver.Engine.legacyScreenSaver/Data/Library/Preferences/com.glouel.Aerial.plist debugMode 1
```

You can find the log afterwards in : `~/Library/Containers/com.apple.ScreenSaver.Engine.legacyScreenSaver/Data/Library/Application Support/Aerial`

I suggest trying to open settings again, via system settings, file should be called `AerialLog.txt`. If you get it, paste it here as it may help.

- Check/wipe your preferences files, please go to :

```~/Library/Containers/com.apple.ScreenSaver.Engine.legacyScreenSaver/Data/Library/Preferences/ByHost```

If you have a file that starts with `com.JohnCoates.Aerial` file, make a copy of it and delete it. 

Then go (one level down) to : 

```~/Library/Containers/com.apple.ScreenSaver.Engine.legacyScreenSaver/Data/Library/Preferences/```

You should definitely have a `com.glouel.Aerial.plist` file. Make a copy then in Terminal : 

```
defaults delete ~/Library/Containers/com.apple.ScreenSaver.Engine.legacyScreenSaver/Data/Library/Preferences/com.glouel.Aerial.plist 
```

This will not only delete the file, but also remove it from macOS cache (if you simply delete the file, you'll need to reboot your mac for new settings to get picked up.

After this, open System Settings (from closed) and try opening Aerial's settings from there. If it works, please send me the 2 plist you saved as this might be key to understanding what is happening to you. 


Again, this is a lot of stuff to try, thanks for your patience on this and for reporting it so I can get to the bottom of it!

**Comment by glouel** [comment] 2023-07-04 13:28
@ckuhtz I believe the issue is specific to Aerial 3.2.7beta1, I'm trying to track down what changes I made that could cause this.

In the meantime, if you switch in companion to not get betas (2nd icon at the bottom row of companion to open settings) then press check now, it will offer to grab 3.2.6 for you and things should work again.  I'll keep you posted as I find a fix hopefully.

**Comment by glouel** [comment] 2023-07-04 16:24
@ckuhtz Ok I can confirm, this is fixed in 3.2.7beta2 now.

**Comment by einsteinbqat** [comment] 2023-07-11 02:44
I have the same problem.
- Open Aerial Settings crashes the Companion
- Clicking on Aerial's Options from the Screen Saver panel of the Settings app does nothing
- Clicking on Aerial's Preview from the Screen Saver panel of the Settings app does nothing

In other words, Aerial is not working for me at all.

Companion: 1.2.2
macOS: 14 (Sonoma)
Mac: Studio 

I would have uploaded a video, but there is a max of 10MB.

**Comment by glouel** [comment] 2023-07-11 03:02
> Companion: 1.2.2 macOS: 14 (Sonoma) Mac: Studio

Ok so, I know it's my fault because I keep delaying the release, but for Sonoma you absolutely need the beta of companion, not much will work with 1.2.2.

Please try this version : https://github.com/AerialScreensaver/AerialCompanion/releases/tag/v1.5.0b8 

And let me know if it fixes your issue. Also see the instruction, make sure you enable beta versions of Aerial so everything works.

**Comment by einsteinbqat** [comment] 2023-07-11 03:16
> > Companion: 1.2.2 macOS: 14 (Sonoma) Mac: Studio
> 
> Ok so, I know it's my fault because I keep delaying the release, but for Sonoma you absolutely need the beta of companion, not much will work with 1.2.2.
> 
> Please try this version : https://github.com/AerialScreensaver/AerialCompanion/releases/tag/v1.5.0b8
> 
> And let me know if it fixes your issue. Also see the instruction, make sure you enable beta versions of Aerial so everything works.

Non

One difference. Now I get a black screen instead of nothing when clicking on Preview.

<img width="592" alt="Screenshot 2023-07-10 at 23 12 49" src="https://github.com/AerialScreensaver/AerialCompanion/assets/48373997/2e08496c-aa4f-4520-8080-5675568bfdcc">

**Comment by glouel** [comment] 2023-07-11 03:52
@einsteinbqat can you close companion, relaunch it, try opening settings from there (icon on the top right). Also try the fullscreen mode from there (the double arrow), see if any of those two works. 

Sonoma can be capricious especially if you have multiple monitors, they are reworking entirely how screen saver works and it's kinda broken. There's a long discussion here if you want more information about the current issues in Sonoma : https://github.com/JohnCoates/Aerial/issues/1305

**Comment by einsteinbqat** [comment] 2023-07-11 04:11
> @einsteinbqat can you close companion, relaunch it, try opening settings from there (icon on the top right). Also try the fullscreen mode from there (the double arrow), see if any of those two works.
> 
> Sonoma can be capricious especially if you have multiple monitors, they are reworking entirely how screen saver works and it's kinda broken. There's a long discussion here if you want more information about the current issues in Sonoma : [JohnCoates/Aerial#1305](https://github.com/JohnCoates/Aerial/issues/1305)

Non

No luck 😄 

Only one screen. Studio Display.

**Comment by glouel** [comment] 2023-07-11 11:47
@einsteinbqat were you using Aerial on this machine prior to Sonoma or is it a fresh install ? I'm trying to narrow it down.

Could you : 
- Close System Settings, close Companion
- open a terminal and enter this command : 
```
open  ~/Library/Containers/com.apple.ScreenSaver.Engine.legacyScreenSaver/Data/Library/Preferences/
```

This will open a finder with some files. 
- Look for `com.glouel.Aerial.plist`, compress it and attach it here in a comment
- if you want to go one step further, still in terminal : 
```
defaults delete ~/Library/Containers/com.apple.ScreenSaver.Engine.legacyScreenSaver/Data/Library/Preferences/com.glouel.Aerial.plist
```

This will wipe the settings and if it's a similar issue should fix it for you. I need the plist though to understand what the issue was for you.

**Comment by einsteinbqat** [comment] 2023-07-11 23:27
> @einsteinbqat were you using Aerial on this machine prior to Sonoma or is it a fresh install ? I'm trying to narrow it down.
> 
> Could you :
> 
> * Close System Settings, close Companion
> * open a terminal and enter this command :
> 
> ```
> open  ~/Library/Containers/com.apple.ScreenSaver.Engine.legacyScreenSaver/Data/Library/Preferences/
> ```
> 
> This will open a finder with some files.
> 
> * Look for `com.glouel.Aerial.plist`, compress it and attach it here in a comment
> * if you want to go one step further, still in terminal :
> 
> ```
> defaults delete ~/Library/Containers/com.apple.ScreenSaver.Engine.legacyScreenSaver/Data/Library/Preferences/com.glouel.Aerial.plist
> ```
> 
> This will wipe the settings and if it's a similar issue should fix it for you. I need the plist though to understand what the issue was for you.

Will do so as soon as I get home

**Comment by einsteinbqat** [comment] 2023-07-11 23:56
@glouel Well… There isn't much in it.

Just this:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>lastVideoCheck</key>
	<string>2023-07-11</string>
</dict>
</plist>

```

**Comment by einsteinbqat** [comment] 2023-07-11 23:59
@glouel OMG Deleting the plist somehow made everything work. LOL

Merci!

**Comment by glouel** [comment] 2023-07-12 00:35
> @glouel OMG Deleting the plist somehow made everything work. LOL
> 
> Merci!

No problem, glad it's fixed. It's very weird that your plist caused issue, I'll investigate, thanks for posting it !

**Comment by einsteinbqat** [comment] 2023-07-12 00:49
> > @glouel OMG Deleting the plist somehow made everything work. LOL
> > Merci!
> 
> No problem, glad it's fixed. It's very weird that your plist caused issue, I'll investigate, thanks for posting it !

@glouel  Don’t rejoice too soon. The app is working (as in I can access the settings), but I have yet to see if the screensaver is actually working. The videos are currently downloading.

Fingers crossed 🤞

**Comment by einsteinbqat** [comment] 2023-07-12 01:13
@glouel

Non.

No dice. The app is working, but the screensaver is not. All the videos are downloaded. When the delay to start the screensaver has elapsed, no video runs. Just a screen.

This is what I see:

![Screenshot 2023-07-11 at 21 05 59](https://github.com/AerialScreensaver/AerialCompanion/assets/48373997/c61ad721-0c0b-43bc-8204-675af61ad24c)


Funny thing is that if I click on Preview, I see a video.

**Comment by einsteinbqat** [comment] 2023-07-12 02:45
@glouel Hahaha! Calvaire!

Had to wait. The latest Sonoma beta fixed Aerials 😄 

Opens Aerials Settings works
Options via macOS Settings works
Screensaver works

E-ve-ry-thing works

**Comment by glouel** [comment] 2023-07-12 11:40
> E-ve-ry-thing works

Enfin!

You didn't confirm, you installed for the first time Aerial on Sonoma on this machine, right ? I'll try to investigate why your plist crashed stuff, it doesn't make much sense. 

Edit : Sadly I can't use your plist, I explicitly asked for a zip of the file, I can't use your cut and paste (it's just a XML representation, not the real file which is binary encoded). If you kept the file, let me know.

**Comment by einsteinbqat** [comment] 2023-07-13 02:29
> > E-ve-ry-thing works
> 
> Enfin!
> 
> You didn't confirm, you installed for the first time Aerial on Sonoma on this machine, right ? I'll try to investigate why your plist crashed stuff, it doesn't make much sense.
> 
> Edit : Sadly I can't use your plist, I explicitly asked for a zip of the file, I can't use your cut and paste (it's just a XML representation, not the real file which is binary encoded). If you kept the file, let me know.

@glouel Installed it twice. The first time, it didn't work. So, I thought that maybe something went wrong with the installation making me decided to delete everything, but was not aware of the plist. On the 2ⁿᵈ install, I went with the 3.2.7 beta. Still didn't work, so I wrote on here. The rest is history.

**Comment by einsteinbqat** [comment] 2023-07-13 21:07
> > E-ve-ry-thing works
> 
> Enfin!
> 
> You didn't confirm, you installed for the first time Aerial on Sonoma on this machine, right ? I'll try to investigate why your plist crashed stuff, it doesn't make much sense.
> 
> Edit : Sadly I can't use your plist, I explicitly asked for a zip of the file, I can't use your cut and paste (it's just a XML representation, not the real file which is binary encoded). If you kept the file, let me know.

No, I trashed it. Sorry. There was only that inside the file.

**Closed as completed** 2023-07-27 11:48 UTC
Labels: question, fix inside
